[2025-06-20T12:43:45.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-20T12:43:45.306+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_dim_match manual__2025-06-20T12:43:41.627914+00:00 [queued]>
[2025-06-20T12:43:45.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_dim_match manual__2025-06-20T12:43:41.627914+00:00 [queued]>
[2025-06-20T12:43:45.326+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-20T12:43:45.379+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_dim_match> on 2025-06-20 12:43:41.627914+00:00
[2025-06-20T12:43:45.386+0000] {standard_task_runner.py:63} INFO - Started process 1162 to run task
[2025-06-20T12:43:45.390+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_transform_to_dwh', 'load_dim_match', 'manual__2025-06-20T12:43:41.627914+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp2wm3n6ky']
[2025-06-20T12:43:45.391+0000] {standard_task_runner.py:91} INFO - Job 214: Subtask load_dim_match
[2025-06-20T12:43:45.502+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_transform_to_dwh.load_dim_match manual__2025-06-20T12:43:41.627914+00:00 [running]> on host 5ea278fdf3a6
[2025-06-20T12:43:45.682+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_transform_to_dwh' AIRFLOW_CTX_TASK_ID='load_dim_match' AIRFLOW_CTX_EXECUTION_DATE='2025-06-20T12:43:41.627914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-20T12:43:41.627914+00:00'
[2025-06-20T12:43:45.685+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-20T12:43:45.704+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-20T12:43:45.705+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 435, in fetch_dim_match
    insert_query = pd.read_sql(""" INSERT INTO dimmatch(hometeam, awayteam, gamedate, arena, city, state, gametype) VALUES(
TypeError: read_sql() missing 1 required positional argument: 'con'
[2025-06-20T12:43:45.722+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_transform_to_dwh, task_id=load_dim_match, run_id=manual__2025-06-20T12:43:41.627914+00:00, execution_date=20250620T124341, start_date=20250620T124345, end_date=20250620T124345
[2025-06-20T12:43:45.767+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 214 for task load_dim_match (read_sql() missing 1 required positional argument: 'con'; 1162)
[2025-06-20T12:43:45.805+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-20T12:43:45.824+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-20T12:43:45.859+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
