[2025-06-21T22:09:27.465+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-21T22:09:27.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-21T22:09:06.261544+00:00 [queued]>
[2025-06-21T22:09:27.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-21T22:09:06.261544+00:00 [queued]>
[2025-06-21T22:09:27.777+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-21T22:09:27.876+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_shot_chart_and_load_to_stage> on 2025-06-21 22:09:06.261544+00:00
[2025-06-21T22:09:27.892+0000] {standard_task_runner.py:63} INFO - Started process 1307 to run task
[2025-06-21T22:09:27.900+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_staging', 'fetch_shot_chart_and_load_to_stage', 'manual__2025-06-21T22:09:06.261544+00:00', '--job-id', '496', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp16hkpipt']
[2025-06-21T22:09:27.903+0000] {standard_task_runner.py:91} INFO - Job 496: Subtask fetch_shot_chart_and_load_to_stage
[2025-06-21T22:09:28.052+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_staging.fetch_shot_chart_and_load_to_stage manual__2025-06-21T22:09:06.261544+00:00 [running]> on host 5ea278fdf3a6
[2025-06-21T22:09:28.270+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_staging' AIRFLOW_CTX_TASK_ID='fetch_shot_chart_and_load_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-21T22:09:06.261544+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-21T22:09:06.261544+00:00'
[2025-06-21T22:09:28.272+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-21T22:09:28.306+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:187 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-21T22:09:31.872+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-22 between BOS and NYK.
[2025-06-21T22:09:39.646+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-22 between LAL and MIN.
[2025-06-21T22:09:46.669+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between DET and IND.
[2025-06-21T22:09:53.521+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between ATL and BRK.
[2025-06-21T22:10:00.653+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between MIA and ORL.
[2025-06-21T22:10:08.439+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between PHI and MIL.
[2025-06-21T22:10:15.217+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between TOR and CLE.
[2025-06-21T22:10:21.871+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between HOU and CHO.
[2025-06-21T22:10:28.343+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between NOP and CHI.
[2025-06-21T22:10:34.816+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between UTA and MEM.
[2025-06-21T22:10:42.379+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between LAC and PHO.
[2025-06-21T22:10:49.020+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-23 between POR and GSW.
[2025-06-21T22:10:55.622+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-24 between WAS and BOS.
[2025-06-21T22:11:02.273+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-24 between DAL and SAS.
[2025-06-21T22:11:09.830+0000] {etl_pipeline.py:205} INFO - Processed game on 2024-10-24 between DEN and OKC.
[2025-06-21T22:11:09.850+0000] {etl_pipeline.py:226} INFO - Column 'x' converted to string type to ensure correct loading.
[2025-06-21T22:11:09.851+0000] {etl_pipeline.py:226} INFO - Column 'y' converted to string type to ensure correct loading.
[2025-06-21T22:11:09.855+0000] {etl_pipeline.py:98} INFO - Ensuring table 'stgshotchart' exists...
[2025-06-21T22:11:09.858+0000] {etl_pipeline.py:100} INFO - Table 'stgshotchart' is ready.
[2025-06-21T22:11:09.859+0000] {etl_pipeline.py:110} INFO - Truncating table stgshotchart and restarting identity columns...
[2025-06-21T22:11:09.912+0000] {etl_pipeline.py:115} INFO - Loading 2692 rows into stgshotchart...
[2025-06-21T22:11:10.009+0000] {etl_pipeline.py:120} ERROR - Database execution error: integer out of range

[2025-06-21T22:11:10.010+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-21T22:11:10.010+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 229, in fetch_and_load_shot_chart_to_stage
    load_df_to_postgres(df=final_df, table_name=table_name, conn_string=conn_string, create_table_query=create_table_query)
  File "/opt/airflow/dags/etl_pipeline.py", line 116, in load_df_to_postgres
    execute_values(cursor, sql_query, data_tuples)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.NumericValueOutOfRange: integer out of range

[2025-06-21T22:11:10.027+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_staging, task_id=fetch_shot_chart_and_load_to_stage, run_id=manual__2025-06-21T22:09:06.261544+00:00, execution_date=20250621T220906, start_date=20250621T220927, end_date=20250621T221110
[2025-06-21T22:11:10.070+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 496 for task fetch_shot_chart_and_load_to_stage (integer out of range
; 1307)
[2025-06-21T22:11:10.119+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-21T22:11:10.135+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-21T22:11:10.168+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
